
# The API key fo webpagetest.org
# Try not to push it to github :)
key = "XXX"

# The start and end index of the domains we're testing
start = 0
end = 100

# Use http://www.webpagetest.org/getLocations.php?f=xml to hunt for locations and UAs
locations = ['Dulles:Firefox', 'Dulles:Chrome']
